name: inferactively
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.10.14=0
  - certifi=2020.11.8=py37hecd8cb5_0
  - cycler=0.10.0=py37_0
  - freetype=2.10.4=ha233b18_0
  - intel-openmp=2019.4=233
  - jpeg=9b=he5867d9_2
  - kiwisolver=1.3.0=py37h23ab428_0
  - lcms2=2.11=h92f6f08_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.1.0=hcb84e12_1
  - lz4-c=1.9.2=h79c402e_3
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py37h181983e_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37h9ed2024_0
  - mkl_fft=1.2.0=py37hc64f4ea_0
  - mkl_random=1.1.1=py37h959d312_0
  - ncurses=6.2=h0a44026_1
  - numpy=1.19.2=py37h456fd55_0
  - numpy-base=1.19.2=py37hcfb5961_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=haf1e3a3_0
  - pandas=1.1.3=py37hb1e8313_0
  - pillow=8.0.1=py37h5270095_0
  - pip=20.3=py37hecd8cb5_0
  - pyparsing=2.4.7=py_0
  - python=3.7.9=h26836e1_0
  - python-dateutil=2.8.1=py_0
  - pytz=2020.4=pyhd3eb1b0_0
  - readline=8.0=h1de35cc_0
  - scipy=1.5.2=py37h912ce22_0
  - seaborn=0.11.0=py_0
  - setuptools=50.3.2=py37hecd8cb5_2
  - six=1.15.0=py37hecd8cb5_0
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py37h9ed2024_0
  - wheel=0.36.0=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
prefix: /Users/at449/anaconda3/envs/inferactively
