[tool.poetry]
name = "pymdp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openpyxl = "^3.0.7"
packaging = "^20.8"
Pillow = "^8.2.0"
pluggy = "^0.13.1"
py = "^1.10.0"
pyparsing = "^2.4.7"
pytest = "^6.2.1"
python-dateutil = "^2.8.1"
pytz = "^2020.5"
scipy = "^1.6.0"
seaborn = "^0.13"
six = "^1.15.0"
toml = "^0.10.2"
typing-extensions = "^4"
xlsxwriter = "^1.4.3"
sphinx-rtd-theme = "^0.4"
myst-nb = "^0.13.1"
autograd = "^1.3"
jax = "^0.4"
equinox = "^0.11"
numpyro = "^0.14"
arviz = "^0.13"
optax = "^0.1"
matplotlib = "^3.9"
networkx = "^3.3"
opencv-python = "^4.10.0.82"
imageio = "^2.34.1"


[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
